version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: skill_recommender_postgres
    environment:
      POSTGRES_DB: skill_recommender_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - skill_recommender_network

  # FastAPI Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skill_recommender_api
    environment:
      - VERSION=1.0.0
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=skill_recommender_dev
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - skill_recommender_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  skill_recommender_network:
    driver: bridge 